import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Payment Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="#">Payment Page</a>
        </h1>


        <div className={styles.grid}>
          <a href="" className={styles.card}>
            <h2>Iphone 13 Pro Max</h2>
            <Image src='/images/apple.png' width={100} height={100} />
            <p>256gb 8gb ram</p>
          </a>

          <a href="" className={styles.card}>
            <h2>One Plus</h2>
            <Image src='/images/huwaei.png' width={100} height={100} />
            <p>512gb 16gb ram</p>
          </a>

          <a href="" className={styles.card}>
            <h2>Samsung F22</h2>
            <Image src='/images/nokia.png' width={100} height={100} />
            <p>128gb 4gb ram</p>
          </a>

          <a href="" className={styles.card}>
            <h2>Redmi 7i</h2>
            <Image src='/images/redmi.png' width={100} height={100} />
            <p>32gb 16gb ram</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
